name: Laravel CI - Development

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  development-check:
    runs-on: self-hosted
    steps:
      - name: 🧾 Checkout Repository
        uses: actions/checkout@v4

      - name: 🐋 Docker Compose Build
        run: docker compose build

      - name: 🗄️ Get Composer Cache Directory
        id: composer-cache
        working-directory: application
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: 💾 Cache Composer Dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('application/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: 🧰 Install Dependencies
        working-directory: application
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: ✨ Run Laravel Pint
        working-directory: application
        run: ./vendor/bin/pint --test
