name: Development DPOS Deploy

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  development-check:
    runs-on: self-hosted
    steps:
      - name: 🧾 Checkout Repository
        uses: actions/checkout@v4

      - name: 🔍 Validate Compose Syntax
        run: docker compose config -q