name: Development DPOS Deploy

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  development-check:
    runs-on: self-hosted
    steps:
      - name: 🧾 Checkout Repository
        uses: actions/checkout@v4

      - name: 🔍 Validate Compose Syntax
        run: docker compose config -q

      - name: 🐋 Up
        run: docker compose -p "test-${{ github.run_id }}" up -d --build

      - name: ✨ Lint
        run: docker compose -p "test-${{ github.run_id }}" exec -T app ./vendor/bin/pint --test

      - name: 🛑 Cleanup
        if: always()
        run: docker compose -p "test-${{ github.run_id }}" down -v