name: Laravel CI - Local Runner

on:
  push:
    branches: [ development ]
  pull_request:

jobs:
  laravel-local-test:
    runs-on: self-hosted
    if: success()
    steps:
      - name: 🧾 Checkout code
        uses: actions/checkout@v3

      - name: 🧰 Install PHP dependencies
        run: composer install --no-interaction --prefer-dist

      - name: ⚙️ Copy .env
        run: cp .env.testing .env

      - name: 🔐 Generate app key
        run: php artisan key:generate

      - name: 🗄️ Run database migrations
        run: php artisan migrate --seed
      - name: ✅ Run Laravel tests
        run: php artisan test  
      - name: Pull latest changes
        run: cd /srv/http && git pull origin development
